include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    require_trailing_commas: true
    always_use_package_imports: true
analyzer:
    exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
